# Generated by Django 5.2.14 on 2026-05-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionbatch',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('LOCKED', 'Locked'), ('ERROR', 'Error')], default='PENDING', max_length=16),
        ),
    ]
